### PR TITLE
GH-182: Allow forcing colored/coloured output

### PR DESCRIPTION
**Pull request by msabramo**
Closes: GH-182

### CODE REVIEW

**Comment by rubik** [comment]
@msabramo Thanks for the contribution Marc! It would be great if we could have a couple of basic tests for this feature. Would you mind adding them (like testing COLOR=yes and COLOR=no at least)? Otherwise, it looks good for merging!

**Comment by msabramo** [comment]
@rubik: Done! I went ahead and amended the commit to add tests and I also changed the commit message to more closely resemble the existing commit messages in the project with the `feat:` prefix and `Fixes #182`.

**Comment by rubik** [comment]
@msabramo Thanks for the contribution Marc, I will release a new version soon!

**Comment by rubik** [comment]
@msabramo Done, I published version 5.1.0 and updated the changelog with your contributions. Thanks again!

**Comment by msabramo** [comment]
You're welcome, @rubik! Thanks for creating and open-sourcing this project!

**Pull request merged**
