### PR TITLE
Jupyter notebook support

### PR DESCRIPTION
**Pull request by tonybaloney**
Replaces #180 (in which I mucked up the merge and broke the previous features)

### CODE REVIEW

**Comment by tonybaloney** [comment]
The tests are running correctly for some reason. I need to isolate the issue before this can be merged

**Comment by rubik** [comment]
@tonybaloney Very nice. Can you add those brief mention of this feature in the README and the docs introduction?

**Comment by tonybaloney** [comment]
I noticed that travis would always pass regardless of Pytest's output, so I've changed the `run.py` script to return pytest's exit code back to the shell.

**Comment by tonybaloney** [comment]
It took me 2 days to figure this out, but there was a module-level mock left behind in one of the test modules! https://github.com/rubik/radon/pull/181/commits/a860a247f5dc869f5ad52d16cd7bb2bcccca8c8c#diff-597c748c01302f443e56785b4a735083R107

This is now ready for review

**Comment by tonybaloney** [comment]
Still have some Python 2 issues to fix first

**Comment by tonybaloney** [comment]
@rubik ready for review.

The test failure on PyPy3.5 is an existing failure

**Comment by rubik** [comment]
@tonybaloney Thanks, it looks good!

**Pull request merged**
