### PR TITLE
Adapt dependency on colorama according to python version

### LINKED ISSUE #193: colorama is pinned to 0.4.1 which conflicts with e.g. twine
In the changes of #185 , the colorama dependency was pinned to 0.4.1 to enable continued support for Python 3.3, 3.4.  However this introduces a conflict with e.g. twine which has a colorama dependency of >=0.4.3.

Would you be willing to support a more complex dependency that is pinned '==0.4.1' for <= Python3.4, and '>=0.4.1' otherwise? 

Thanks.

### PR DESCRIPTION
**Pull request by douardda**
fix #193

### CODE REVIEW

**Comment by douardda** [comment]
The travis failure seems completely unrelated with the PR, seems  pypy tests are broken...

**Comment by richardpen** [comment]
Any updates here or is there any workaround, It's also impacting other library? Would love to get this merged.

**Comment by rubik** [comment]
@douardda Thanks a lot, I'll merge this and release a new version shortly.

**Comment by rubik** [comment]
@douardda @richardpen I published Radon v4.2.0 on PyPI.

**Pull request merged**
