### PR TITLE
Support file configuration overrides

### PR DESCRIPTION
**Pull request by tonybaloney**
This is a work-in-progress so that I can get some feedback from @rubik 

Typically, the CLI flags should override the file-configuration.

This design will have the following precedence:
1. CLI flags
2. `setup.cfg`
3.  `~/.radon.cfg`
4. `radon.cfg`

However, because the defaults CLI options are in the kwarg defaults in the function signatures, this won't work. I'm going to have to refactor the commands so that they default to None, and the default values are elsewhere.

Just checking, @rubik do you want the CLI to override any .cfg options?

### CODE REVIEW

**Comment by tonybaloney** [comment]
This also exposes another question. The config will default to providing properties as strings, it has no awareness of types. 
I can't see any major issue with this other than the min/max CC options. Which I'll test more thoroughly.

**Comment by rubik** [comment]
Thanks for starting this!

I think your plan is good, there are two side-effects from changing the defaults to None:
1. the type conversion will not happen automatically anymore, so it will need to be done after reading and merging the options, before passing them to the functions;
2. the output of `radon --help` will change slightly, even though it shouldn't be too much of a problem. The best way would be to just drop the `mando` dependency altogether and go back to argparse. I don't think the advantages that mando provide outweigh the reduction in clarity. That's a different PR though, it's best not to mix things.

**Comment by tonybaloney** [comment]
@rubik
I think this modification solves those 2 issues.

Because of the way that `mando` sets the default arguments, it has to be done in the function declaration.
So I've changed the function declaration, so that it sets the default to whatever is in the configuration file (if it exists).

However, there is one side-effect. The configuration is loaded at module-import. This isn't an issue for radon generally, because it's CLI, and because it's highly unlikely someone would import radon, change the configuration, then expect it to behave differently.
It does prove a challenge for the testing, so I've got one test. But once `mando` is removed this would be refactored into a `main()` function.

**Comment by tonybaloney** [comment]
Ready for review

**Comment by rubik** [comment]
@tonybaloney I think it looks good, thanks for the contribution! I will add your name to the changelog file before releasing.

**Pull request merged**
