### PR TITLE
Fix for issue 109 and 110

### PR DESCRIPTION
**Pull request by zukoj**

### CODE REVIEW

**Comment by ashanbrown** [comment]
@zukoj: Could you paste a simple example of the issue here or add a test case that illuminates the issue?  I'd like to understand the issue a bit better.   Thanks.

**Comment by zukoj** [comment]
Well here's a log that I attached to the issue. It doesn't make sense that the LOC is smaller than the SLOC.
[Error.log.txt](https://github.com/rubik/radon/files/901263/Error.log.txt)

**Comment by ashanbrown** [comment]
@zukoj I saw the log but I couldn't find the input file is checking.  Is that in the tree somewhere?

**Comment by zukoj** [comment]
@ashanbrown No it isn't, that's one of my projects at work but I tried it on the raw.py file and got the same result so you can try that.

**Comment by rubik** [comment]
Basically the last PR changed the definition of LOC and this one is changing it back as it was before.

Essentially, it boils down to deciding what LOC and SLOC are, and the problem is that this not fixed even in the relevant literature. [The Wikipedia article](https://en.wikipedia.org/wiki/Source_lines_of_code) on SLOC confirms that there are varying definitions in use. I propose to define the two concepts once and for all (in relation to this project) and then make it clear in the documentation.

**Comment by zukoj** [comment]
@rubik If you want to keep LOC the way it was, then we can add a new line PLOC (which stands for physical lines of code) and that contains the actual complete lines of code count.

**Comment by rubik** [comment]
@zukoj I'm not really in favour of adding yet another acronym since the current situation is very blurry. I think @ashanbrown suggestion of fixing LOC meaning is better in this regard.

**Comment by rubik** [comment]
Hi @zukoj, issue #110 has been fixed by Andrew, so I committed your changes regarding comment stats summary manually. Therefore I can close this PR.

**Pull request closed without merging**
