### PR TITLE
Added support of match pattern

### PR DESCRIPTION
**Pull request by DolajoCZ**
Added support of match pattern introduced in python 3.10. @rubik comments/proposals are welcomed.

### CODE REVIEW

**Comment by PedanticHacker** [comment]
This is a very welcomed and also a very much needed addition to radon. @DolajoCZ, thank you for this PR.

I would like to know whether "case _:"  is treated the same way as "else:" is, i.e., it should not add complexity. Is that the case here? It wasn't obvious to me in this PR's code that I've read.

**Comment by PedanticHacker** [comment]
Why is this still an open PR and not a merged one? Also, why is radon so slow at releasing a new version?

**Comment by PedanticHacker** [comment]
@rubik, are you still alive?

**Comment by rubik** [comment]
@DolajoCZ Thanks for the contribution, much appreciated. It would be great if you could document this addition in the table on this page:
https://github.com/rubik/radon/blob/master/docs/intro.rst

The PR is otherwise ready for merging.

@PedanticHacker I am indeed alive, I'm just very busy. If you want to help maintain the project let me know.

**Comment by PedanticHacker** [comment]
@rubik, it would actually be an honor for me to contribute to this project. I'm using *radon* quite often to test cyclomatic complexity in my chess GUI app named SuperChess, so I'd like to give back to the community.

**Comment by mkokotovich** [comment]
Any updates on this PR? I just found radon - what an awesome tool. It would be great if this PR was merged and a new release was issued to fully support python 10!

**Comment by 7ovana** [comment]
Do we have an update on this one? Without it cyclomatic complexity is still wrongly detected as O(1) for `match` . 
@rubik

**Comment by PedanticHacker** [comment]
This is batshit crazy to abandon a project like radon. It’s a very good tool.

**Comment by rubik** [comment]
@DolajoCZ Thanks for the contribution, I finally got around to take a look again and merge it. Apologies everyone for the lack of maintenance, I've been very busy with personal and work commitments.

**Comment by StevenMapes** [comment]
Which version was this release as part of as I still have issues with match producing errors when running with 6.0.1

**Pull request merged**
