### PR TITLE
- added show closures to flake8

### PR DESCRIPTION
**Pull request by franzhaas**
Hi,

i really like this tool integrated with flake8.
I would like to have the show closures option available in the flake8 plugin, this pull request brings this ability.

Thanks for the great tool,
Franz

### CODE REVIEW

**Comment by rubik** [comment]
Thank you for taking the time to submit a PR, much appreciated!

Do you need a new version on PyPI after this change?

**Comment by franzhaas** [comment]
Hi.

Thanks for merging.

no thank you, i do not need a new version on pypi (now).
I do have issues specifying the  show closures option in the config file... I want to figure that out first. 

Thanks,
Franz

**Comment by franzhaas** [comment]
Hi,

I found the issue, it was inside the config file. Never mind.

Yes please, I would love a pypi release, that would be great.

Thanks,
Franz

2018-01-08 18:42 GMT+01:00 Michele Lacchia <notifications@github.com>:

**Comment by rubik** [comment]
Done, version 2.2.0 is on PyPI. Thanks for the contribution!

**Pull request merged**
