### PR TITLE
Python config parser compatibility to 2.*

### PR DESCRIPTION
**Pull request by edwinelisia**

### CODE REVIEW

**Comment by edwinelisia** [comment]
CI failed on pypy3.5. Testing it locally shows this: 
```
20:48 $ make tests
python radon/tests/run.py
==================================================================== test session starts ====================================================================
platform darwin -- Python 3.5.3[pypy-7.0.0-final], pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /workspace/radon
plugins: mock-3.1.0
collected 392 items

radon/tests/test_cli.py ..............                                                                                                                [  3%]
radon/tests/test_cli_harvest.py ..................                                                                                                    [  8%]
radon/tests/test_cli_tools.py ...........                                                                                                             [ 10%]
radon/tests/test_complexity_utils.py ...............................................................................................................  [ 39%]
radon/tests/test_complexity_visitor.py ............................................................                                                   [ 54%]
radon/tests/test_halstead.py ..........                                                                                                               [ 57%]
radon/tests/test_ipynb.py .....                                                                                                                       [ 58%]
radon/tests/test_other_metrics.py ................................................................................................................    [ 86%]
radon/tests/test_raw.py ...................................................                                                                           [100%]

==================================================================== 392 passed in 3.62s ====================================================================

```

20:56 $ make tests
python radon/tests/run.py
==================================================================== test session starts ====================================================================
platform darwin -- Python 3.5.3[pypy-5.10.1-final], pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /workspace/radon
plugins: mock-3.1.0
collected 392 items

radon/tests/test_cli.py ..............                                                                                                                [  3%]
radon/tests/test_cli_harvest.py ..................                                                                                                    [  8%]
radon/tests/test_cli_tools.py ...........                                                                                                             [ 10%]
radon/tests/test_complexity_utils.py ...............................................................................................................  [ 39%]
radon/tests/test_complexity_visitor.py ............................................................                                                   [ 54%]
radon/tests/test_halstead.py ..........                                                                                                               [ 57%]
radon/tests/test_ipynb.py .....                                                                                                                       [ 58%]
radon/tests/test_other_metrics.py ................................................................................................................    [ 86%]
radon/tests/test_raw.py ...................................................                                                                           [100%]

==================================================================== 392 passed in 4.17s ====================================================================

@rubik Can you take a look? When are you thinking of cutting a new release?

**Comment by rubik** [comment]
@edwinelisia Thanks for the fix, I will take a look today and release a new version.

**Comment by rubik** [comment]
I published Radon v4.2.0 on PyPI.

**Comment by edwinelisia** [comment]
Thanks @rubik !

**Pull request merged**
